osx_image: xcode8
language: objective-c

before_install:
- pod update RemoteLogger

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail && env NSUnbufferedIO=YES
    xcodebuild test
    -workspace ReaderExampleSwift.xcworkspace
    -scheme ReaderExampleSwift
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
